name: publish basic container

on:
  release:
    types: [published]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.BACK_IMAGE_NAME }}:latest
            ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.BACH_IMAGE_NAME }}:${{ github.ref_name }}
      

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./client
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.FRONT_IMAGE_NAME }}:latest
            ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.FRONT_IMAGE_NAME }}:${{ github.ref_name }}
